### ISSUE TITLE
Check for AzureRM module in favor of Az due to ParametersException. 

### ISSUE THREAD

**Issue by autocloudarc** [autocloudarc/0026-azure-automation-plus-dsc-lab#3]
#6cfc08c As of 24 FEB 2019, when using the new Az modules, an error stating that the https: drive cannot be mapped is generated. It seems that the New-AzResourceGroupDeployment cmdlet will incorrectly interpret the '**https:**' part of $templateUri = '**https:**//raw.githubusercontent.com/autocloudarc/0026-azure-automation-plus-dsc-lab/master/azuredeploy.json' as a PSDrive instead of as part of a URL. As a workaround I committed the #6cfc08c change to use the original AzureRM Cmdlet instead, New-AzureRmResourceGroupDeployment (not the aliased version that points to New-AzResourceGroupDeployment).

The error condition that was generated on 24 FEB 2019 is:

`New-AzResourceGroupDeployment : Cannot retrieve the dynamic parameters for the cmdlet. Cannot find drive. A drive with the name 'https' does not exist.
At <line number...>
+ New-AzResourceGroupDeployment -ResourceGroupName <ResourceGroupName>
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-AzResourceGroupDeployment], ParameterBindingException
    + FullyQualifiedErrorId : GetDynamicParametersException,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet`

**Comment by JulianHayward** [comment]
is there any Progress on this bug?

**Comment by tjgalama** [comment]
I also happen to run into this exception. After some investigation I noticed that passing $templateUri worked in the old version:
`New-AzureRMResourceGroupDeployment -templateFile $templateUri `
But with the new `New-AzResourceGroupDeployment` this caused the exception you mentioned.
However, when calling the new method with the named argument `templateUri` instead of `templateFile`, it worked like a charm:
`New-AzResourceGroupDeployment -templateUri $templateUri `
perhaps this solves your problem

**Comment by autocloudarc** [comment]
Thanks for the feedback tjgalama. :-) I plan to test this eventually, since I haven't looked at this code in a while.
